### ISSUE TITLE
依赖安装缺少babel-preset-es2015

### ISSUE THREAD

**Issue by wangtaigong** [huxiaocheng/vue-gn-components#11]
依赖安装后,运行yarn serve的时候, 会报错误
安装工具: yarn 

 ERROR  Error: Cannot find module 'babel-preset-es2015' from 'F:\github\vue-gn-components'
Error: Cannot find module 'babel-preset-es2015' from 'F:\github\vue-gn-components'
    at Function.resolveSync [as sync] (F:\github\vue-gn-components\node_modules\resolve\lib\sync.js:90:15)
    at resolveStandardizedName (F:\github\vue-gn-components\node_modules\@babel\core\lib\config\files\plugins.js:101:31)
    at resolvePreset (F:\github\vue-gn-components\node_modules\@babel\core\lib\config\files\plugins.js:58:10)
    at loadPreset (F:\github\vue-gn-components\node_modules\@babel\core\lib\config\files\plugins.js:77:20)
    at createDescriptor (F:\github\vue-gn-components\node_modules\@babel\core\lib\config\config-descriptors.js:154:9)
    at F:\github\vue-gn-components\node_modules\@babel\core\lib\config\config-descriptors.js:109:50
    at Array.map (<anonymous>)
    at createDescriptors (F:\github\vue-gn-components\node_modules\@babel\core\lib\config\config-descriptors.js:109:29)
    at createPresetDescriptors (F:\github\vue-gn-components\node_modules\@babel\core\lib\config\config-descriptors.js:101:10)
    at presets (F:\github\vue-gn-components\node_modules\@babel\core\lib\config\config-descriptors.js:47:19)
error Command failed with exit code 1.

我本地的解决方式:  1,安装@babel/preset-env  2,将.babelrc中的presets中babel-preset-es2015修改为@babel/preset-env

**Comment by fansjay** [comment]
大佬 厉害



在 2020-11-15 10:47:11，"wangtaigong" <notifications@github.com> 写道：

依赖安装后,运行yarn serve的时候, 会报错误
安装工具: yarn

ERROR Error: Cannot find module 'babel-preset-es2015' from 'F:\github\vue-gn-components'
Error: Cannot find module 'babel-preset-es2015' from 'F:\github\vue-gn-components'
at Function.resolveSync [as sync] (F:\github\vue-gn-components\node_modules\resolve\lib\sync.js:90:15)
at resolveStandardizedName (F:\github\vue-gn-components\node_modules@babel\core\lib\config\files\plugins.js:101:31)
at resolvePreset (F:\github\vue-gn-components\node_modules@babel\core\lib\config\files\plugins.js:58:10)
at loadPreset (F:\github\vue-gn-components\node_modules@babel\core\lib\config\files\plugins.js:77:20)
at createDescriptor (F:\github\vue-gn-components\node_modules@babel\core\lib\config\config-descriptors.js:154:9)
at F:\github\vue-gn-components\node_modules@babel\core\lib\config\config-descriptors.js:109:50
at Array.map ()
at createDescriptors (F:\github\vue-gn-components\node_modules@babel\core\lib\config\config-descriptors.js:109:29)
at createPresetDescriptors (F:\github\vue-gn-components\node_modules@babel\core\lib\config\config-descriptors.js:101:10)
at presets (F:\github\vue-gn-components\node_modules@babel\core\lib\config\config-descriptors.js:47:19)
error Command failed with exit code 1.

我本地的解决方式: 1,安装@babel/preset-env 2,将.babelrc中的presets中babel-preset-es2015修改为@babel/preset-env
